# Generated by Django 3.1.7 on 2021-02-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(max_length=10)),
                ('name', models.TextField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
    ]
